services:
  # Backend API
  - type: web
    name: pseudoqui-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5000

  # Frontend
  - type: web
    name: pseudoqui-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
